name: flutter_assets_generator
description: Automatically generate a resource file by scanning pubspec.yaml to correspond to the flutter's asset, imitation R file short name.
version: 0.0.7
homepage: https://github.com/goodswifter/flutter_assets_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  args: ^2.1.1
  dart_style: ^2.0.2
  glob: ^2.0.1
  io: ^1.0.3
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.1

executables:
  fgen: flutter_assets_generator
